import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';

let db: PGlite;
const admin='00000000-0000-4000-8000-000000000001';
const alice='00000000-0000-4000-8000-000000000002';
const bob='00000000-0000-4000-8000-000000000003';
async function asUser(id:string){await db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role authenticated;`);}
async function rpc(name:string,args:unknown[]=[]){const result=await db.query<{result:Record<string,unknown>}>(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')}) as result`,args);return result.rows[0].result;}
beforeAll(async()=>{
  db=new PGlite();
  await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,phone text,phone_confirmed_at timestamptz); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid; $$; grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
  await db.exec(readFileSync('supabase/migrations/20261006051913_loyalty_core.sql','utf8').split('-- STORAGE SETUP')[0]);
  await db.exec(readFileSync('supabase/migrations/20261006055246_customer_name_phone_entry.sql','utf8'));
  await db.exec(`insert into auth.users values('${admin}',null,null),('${alice}',null,null),('${bob}',null,null); insert into public.profiles(id,role,name) values('${admin}','admin','Owner');`);
},30000);
afterAll(async()=>{await db.close();});
describe('Loyalty database rules',()=>{
  it('creates one profile and card from name and number without OTP',async()=>{await asUser(alice);expect((await rpc('register_customer',['Arun','+919876543210'])).phone).toBe('+919876543210');await rpc('register_customer',['Arun','+919876543210']);await rpc('ensure_customer',[null]);const rows=await db.query('select * from public.loyalty_cycles');expect(rows.rows).toHaveLength(1);await asUser(bob);expect((await rpc('register_customer',['Impersonator','+919876543210'])).error).toMatch(/already has a card/);await rpc('register_customer',['Priya','+919876543211']);});
  it('does not let a session switch to someone else’s phone',async()=>{await asUser(alice);expect((await rpc('register_customer',['Arun','+919876543211'])).error).toMatch(/existing card/);expect((await rpc('ensure_customer',[null])).phone).toBe('+919876543210');});
  it('denies customer admin RPCs and direct role/stamp writes',async()=>{await asUser(alice);expect((await rpc('generate_loyalty_code',['1234AB'])).error).toBeTruthy();expect((await rpc('admin_overview')).error).toBeTruthy();await expect(db.exec("update public.profiles set role='admin'")).rejects.toThrow(/permission denied/);await expect(db.exec('update public.loyalty_cycles set completed_checkpoints=5')).rejects.toThrow(/permission denied/);});
  it('creates a code with exactly five minutes expiry, reusing the current code',async()=>{await asUser(admin);const code=await rpc('generate_loyalty_code',['1234AB']);expect(Date.parse(code.expires_at as string)-Date.parse(code.created_at as string)).toBe(300000);expect((await rpc('generate_loyalty_code',['1234AC'])).code).toBe('1234AB');});
  it('accepts a code once per customer and allows other customers to use it',async()=>{await asUser(alice);expect((await rpc('validate_loyalty_code',['1234AB'])).checkpoint).toBe(1);expect((await rpc('validate_loyalty_code',['1234AB'])).error).toMatch(/already/);await asUser(bob);expect((await rpc('validate_loyalty_code',['1234AB'])).checkpoint).toBe(1);});
  it('isolates customer records and conceals codes with RLS',async()=>{await asUser(alice);expect((await db.query('select * from public.profiles')).rows).toHaveLength(1);expect((await db.query('select * from public.loyalty_codes')).rows).toHaveLength(0);expect((await db.query('select * from public.loyalty_checkins')).rows).toHaveLength(1);});
  it('rejects expired codes and previous-day codes',async()=>{await db.exec(`reset role; insert into public.loyalty_codes(code,created_by,created_at,expires_at) values('2345AB','${admin}',now()-interval '5 minutes',now()); insert into public.loyalty_codes(code,created_by,created_at,expires_at,created_date) values('2345AC','${admin}',now(),now()+interval '5 minutes',(now() at time zone 'Asia/Kolkata')::date-1);`);await asUser(alice);expect((await rpc('validate_loyalty_code',['2345AB'])).error).toMatch(/expired/);expect((await rpc('validate_loyalty_code',['2345AC'])).error).toMatch(/expired/);});
  it('unlocks a reward on the sixth stamp and preserves its snapshot',async()=>{await db.exec(`reset role; update public.rewards set name='Chicken Noodles';`);for(let i=2;i<=6;i++){await db.exec(`reset role; insert into public.loyalty_codes(code,created_by,created_at,expires_at) values('100${i}AB','${admin}',now(),now()+interval '5 minutes');`);await asUser(alice);const r=await rpc('validate_loyalty_code',[`100${i}AB`]);expect(r.checkpoint).toBe(i);expect(r.rewardUnlocked).toBe(i===6);}await db.exec("reset role; update public.rewards set name='New dish';");await asUser(alice);const cycles=await db.query<{reward_name:string;status:string}>('select * from public.loyalty_cycles');expect(cycles.rows[0].reward_name).toBe('Chicken Noodles');expect(cycles.rows[0].status).toBe('completed');});
  it('blocks extra stamps until an admin claims, then resets without deleting history',async()=>{await db.exec(`reset role; delete from private.validation_limits where customer_id='${alice}'; insert into public.loyalty_codes(code,created_by,created_at,expires_at) values('1007AB','${admin}',now(),now()+interval '5 minutes');`);await asUser(alice);expect((await rpc('validate_loyalty_code',['1007AB'])).error).toMatch(/claim/);const cycle=(await db.query<{id:string}>('select id from public.loyalty_cycles')).rows[0];expect((await rpc('claim_reward',[cycle.id])).error).toBeTruthy();await asUser(admin);expect((await rpc('claim_reward',[cycle.id])).success).toBe(true);expect((await rpc('claim_reward',[cycle.id])).error).toMatch(/already/);await asUser(alice);const cycles=await db.query<{status:string;completed_checkpoints:number}>('select * from public.loyalty_cycles order by cycle_number');expect(cycles.rows.map(c=>[c.status,c.completed_checkpoints])).toEqual([['reward_claimed',6],['active',0]]);expect((await db.query('select * from public.loyalty_checkins')).rows).toHaveLength(6);expect((await rpc('validate_loyalty_code',['1234AB'])).error).toMatch(/already/);});
  it('persists failed attempts and rate limits guessing',async()=>{await db.exec(`reset role; delete from private.validation_limits where customer_id='${bob}';`);await asUser(bob);for(let i=0;i<10;i++)expect((await rpc('validate_loyalty_code',['9999ZZ'])).error).toBeTruthy();expect((await rpc('validate_loyalty_code',['9999ZZ'])).rateLimited).toBe(true);});
  it('returns real dashboard counts to admins',async()=>{await asUser(admin);const data=await rpc('admin_overview');expect(data.stats).toMatchObject({customers:2,completedCards:1,claimedRewards:1,visits:7});expect(data.chart).toHaveLength(7);});
  it('denies anonymous execution of privileged functions',async()=>{await db.exec("reset role; select set_config('request.jwt.claim.sub','',false); set role anon;");await expect(rpc('validate_loyalty_code',['1234AB'])).rejects.toThrow(/permission denied/);await expect(rpc('ensure_customer',['Stranger'])).rejects.toThrow(/permission denied/);expect((await db.query('select * from public.shop_settings')).rows).toHaveLength(1);});
});
